# Generated by Django 3.1.7 on 2021-03-21 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unternehmensname', models.CharField(default='--', max_length=100)),
                ('vorodernach', models.CharField(default='--', max_length=20)),
                ('tweetsanzahl', models.IntegerField(default=0)),
                ('woerteranzahl', models.IntegerField(default=0)),
                ('zeichenanzahl', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Details',
                'verbose_name_plural': 'Details',
            },
        ),
        migrations.CreateModel(
            name='unternehmena',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unternehmensname', models.CharField(default='--', max_length=100)),
                ('userId', models.CharField(default='--', max_length=100)),
                ('datum', models.CharField(default='--', max_length=20)),
                ('tweet', models.TextField(default='--', max_length=280)),
                ('zeichen', models.IntegerField(default=0)),
                ('woerter', models.IntegerField(default=0)),
                ('schluesselId', models.CharField(default='', editable=False, max_length=100)),
                ('vorodernach', models.CharField(default='--', editable=False, max_length=5)),
            ],
            options={
                'verbose_name': 'Data Breaches',
                'verbose_name_plural': 'Data Breaches',
            },
        ),
    ]
