# Generated by Django 3.1.7 on 2021-03-24 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unternehmen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='average_words',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='details',
            name='tweets_after_10_days',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='details',
            name='tweets_after_20_days',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='details',
            name='tweets_after_30_days',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='details',
            name='tweets_per_30_days',
            field=models.FloatField(default=0),
        ),
    ]
