# Generated by Django 3.1.7 on 2021-05-02 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unternehmen', '0004_auto_20210328_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweets',
            name='tweet',
        ),
    ]
