# Generated by Django 3.1.7 on 2021-05-02 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unternehmen', '0005_remove_tweets_tweet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='zeichenanzahl',
        ),
        migrations.RemoveField(
            model_name='tweets',
            name='zeichen',
        ),
    ]
